=== apache/openoffice-org/content/tools/builds/builds.dtd
<!ELEMENT builds (branch+,type_description*)>
<!ELEMENT branch (cvs_tag, tarball_tag?, status, description, type, cygwin?, macos?, jdk141?, gcc295?)>
<!ELEMENT cvs_tag (#PCDATA)>
<!ELEMENT tarball_tag (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT cygwin (#PCDATA)>
<!ELEMENT macos (#PCDATA)>
<!ELEMENT jdk141 (#PCDATA)>
<!ELEMENT gcc295 (#PCDATA)>
<!ELEMENT type_description (code, short_name, long_description)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT short_name (#PCDATA)>
<!ELEMENT long_description (p+)>
<!ELEMENT p (#PCDATA|a)*>
<!ELEMENT a (#PCDATA) >
<!ATTLIST a href CDATA #REQUIRED >

=== apache/openoffice-org/content/tools/builds/builds.xml
<?xml version="1.0"?>
<!DOCTYPE builds SYSTEM "builds.dtd">
<builds>
<branch>
<cvs_tag>OOO_STABLE_1</cvs_tag>
<tarball_tag>OpenOffice_1_0_2</tarball_tag>
<status>Active</status>
<description>Stable release 21 jan 2003</description>
<type>stable</type>
<macos>No</macos>
<jdk141>No</jdk141>
<gcc295>No</gcc295>
</branch>
<branch>
<cvs_tag>OOO_STABLE_1_PORTS</cvs_tag>
<tarball_tag>Not applicable</tarball_tag>
<status>Active</status>
<description>Where porters hang out</description>
<type>Porting</type>
<macos>Yes</macos>
<jdk141>No</jdk141>
<gcc295>???</gcc295>
</branch>
<branch>
<cvs_tag>cws_srx644_ooo20030309</cvs_tag>
<tarball_tag>Not Applicable</tarball_tag>
<status>Active</status>
<description>New release of 644 for developers</description>
<type>developer</type>
<macos>No</macos>
<jdk141>Yes</jdk141>
<gcc295>???</gcc295>
</branch>
<branch>
<cvs_tag>mws_cws_644</cvs_tag>
<tarball_tag>Not applicable</tarball_tag>
<status>Internal</status>
<description>Star Office branch of 644 branch</description>
<type>developer</type>
<macos>No</macos>
<jdk141>Yes</jdk141>
<gcc295>No</gcc295>
</branch>
<branch>
<cvs_tag>cws_srx644_ooo11beta</cvs_tag>
<status>bleeding</status>
<description>stable release of 644 for developers</description>
<type>developer</type>
<cygwin>No</cygwin>
<macos>No</macos>
<jdk141>???</jdk141>
<gcc295>???</gcc295>
</branch>
<branch>
<cvs_tag>cws_srx644_ooo20030223</cvs_tag>
<status>archive</status>
<description>Integration branch 644 branch for OpenOffice.org</description>
<type>Developer</type>
</branch>
<branch>
<cvs_tag>OO643C</cvs_tag>
<status>archive</status>
<description>General development branch, includes pdf export</description>
<type>developer</type>
</branch>
<type_description>
<code>developer</code>
<short_name>Developers branch</short_name>
<long_description>
<p>A developers branch is where most hacking is done.  This has the most
open policy for applying patches and it is typically where new features are
developed and debugged.</p>
<p>The good side to this is that you have the lastest features, the down side
is that you get the side effects of the changes.  We don't discourage you from
working here but you can expect problems at times.</p>
<p>Developer releases are merged back to stable on a semi regular basis. All
features migrated to <a href="#stable">stable</a> must be exactly that.</p>
</long_description>
</type_description>
<type_description>
<code>stable</code>
<short_name>Stable branch</short_name>
<long_description>
<p>A stable branch is base for a release build of the OpenOffice.org product.
This is where bug fix tracking takes place. The policy on these branchs are to
fix functional errors only.</p>
<p>The good side is that any patches are more thoroughly vetted before going
into a stable release therefore you have fewer mystery bugs.  The downside is
that there are fewer features and some bug fixes are already in the developer
release.</p>
</long_description>
</type_description>
<type_description>
<code>port</code>
<short_name>Porting branch</short_name>
<long_description>
<p>This is where a lot of 
<a href="http://porting.openoffice.org">porting</a> to new platforms
occurs.  There are few features added in these branches and sometimes they are
very outdated in terms of functionality as a port needs some stability so that
they are not solving new problems but working to an end goal together.</p>
<p>Features that are added are to help support that platform for example adding
a new way of calling windowing functions for example coding Mac OS aqua calls
instead of X windows calls.</p>
<p>This is a branch used for platforms that are not yet part of the official
release platforms, including Mac OSX, Irix, Linux s390.</p>
<p>Some platforms have problems with the gcc version 3 compilers, for example
<a href="http://porting.openoffice.org/irix/">Irix</a>
and <a href="http://porting.openoffice.org/mac/">Mac</a>.  Please
investigate the respective porting pages before trying anything.</p>
</long_description>
</type_description>
</builds>
